using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

public static class ObjectHeadServerCatalogExporter
{
    [MenuItem("Object Head/Network/Export Server Catalog")]
    public static void Export()
    {
        var catalog=ObjectHeadContent.Load();
        if(catalog==null || catalog.characters.Length==0 || catalog.maps.Length==0)throw new InvalidOperationException("Missing content catalog");
        if(catalog.characters.Select(c=>c.kind).Distinct().Count()!=catalog.characters.Length ||
           catalog.maps.Select(m=>m.id).Distinct().Count()!=catalog.maps.Length ||
           catalog.modes.Select(m=>m.mode).Distinct().Count()!=catalog.modes.Length)
            throw new InvalidOperationException("Duplicate server catalog IDs");
        var text=new StringBuilder("-- Generated from ObjectHeadContent by Export Server Catalog. Do not edit this file.\nreturn {\n  ruleset = ");
        text.Append(Quote(ObjectHeadNetworkManager.AuthorityRuleset)).Append(",\n  characters = { ");
        text.Append(string.Join(", ",catalog.characters.OrderBy(c=>(int)c.kind).Select(c=>$"[{(int)c.kind}]=true")));
        text.Append(" },\n  maps = { ").Append(string.Join(", ",catalog.maps.Select(m=>Quote(m.id)))).Append(" },\n  modes = {\n");
        foreach(var mode in catalog.modes.OrderBy(m=>(int)m.mode))
        {
            int count=catalog.CharactersPerPlayer(mode.players);
            if(count<=0 || mode.alliances.Length!=mode.players || mode.spawnSeats.Length!=mode.players)
                throw new InvalidOperationException("Invalid team rule: "+mode.mode);
            text.Append($"    [{(int)mode.mode}] = {{ players={mode.players}, characters={count} }},\n");
        }
        text.Append("  }\n}\n");
        Directory.CreateDirectory("Server/Nakama/modules");
        File.WriteAllText("Server/Nakama/modules/authority_catalog.lua",text.ToString(),new UTF8Encoding(false));
        UnityEngine.Debug.Log("[Authority] Server admission catalog exported from Unity content.");
    }
    private static string Quote(string value)
    {
        if(string.IsNullOrEmpty(value) || value.Any(c=>!(char.IsLetterOrDigit(c)||c=='_'||c=='-')))
            throw new InvalidOperationException("Map IDs must be alphanumeric, underscore or hyphen");
        return "\""+value+"\"";
    }
}
