-- Generated from ObjectHeadContent by Export Server Catalog. Do not edit this file.
return {
  ruleset = "authority-0916-v2",
  characters = { [0]=true, [1]=true, [2]=true, [3]=true, [4]=true, [5]=true },
  maps = { "wind_meadow", "twin_citadels", "shattered_reef" },
  modes = {
    [0] = { players=2, characters=3 },
    [1] = { players=4, characters=1 },
    [2] = { players=4, characters=1 },
  }
}
