-- Generated from ObjectHeadContent by Export Server Catalog. Do not edit this file.
return {
  ruleset = "authority-0916-v2",
  characters = { [0]=true, [1]=true, [2]=true, [3]=true, [4]=true, [5]=true, [6]=true },
  common_slots = 6,
  maps = { "wind_meadow", "twin_citadels", "shattered_reef", "tidal_caverns", "sky_terraces", "low_cavern" },
  modes = {
    [0] = { players=2, characters=3 },
    [1] = { players=4, characters=2 },
    [2] = { players=4, characters=2 },
  }
}
